### ISSUE TITLE
can't run sleepy from command line with arguments in msys2

### ISSUE THREAD

**Issue by ellisonch** [CyberShadow/verysleepy#15]
When I try running sleepy from the command line with arguments in msys2, I get an error:

`$ sleepy /r:a.exe`
![image](https://cloud.githubusercontent.com/assets/1285287/6200099/8b6389c0-b436-11e4-8495-16843ea3f7bb.png)

The same thing happens if I surround `a.exe` with quotes.

Even running `sleepy /h` fails:
![image](https://cloud.githubusercontent.com/assets/1285287/6200120/84417764-b437-11e4-8cd6-d65c3b7d2cbe.png)
Though it is a little revealing, because something turned "/h" into "H:\"

If instead I call "cmd", and have it run sleepy, everything works:
`cmd /C "sleepy /r:a.exe"`

And I can pass program arguments like:
`cmd /C "sleepy /r:\"a.exe foo\""`

I tested it from cygwin, and cygwin is able to run sleepy fine directly, without needing to go through `cmd`.

I'm installed msys2 from msys2-x86_64-20141113.exe and I have windows 7.

**Comment by CyberShadow** [comment]
If you run Very Sleepy with `/h`, is created with this command line:

`"C:\Program Files\Very Sleepy 0.90\sleepy.exe" H:/`

Thus, msys2 is translating the /h parameter, which it thinks of as a Unix path, into a Windows path.

**Comment by ellisonch** [comment]
You're right!  In case it might help others, it seems like using an extra "/" to escape works.  So, `sleepy //h` works just fine.

Thanks!
